#!/usr/bin/env python3
"""Read-only checks for the Tindol Family Hub cross-CLI scaffold."""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
REGISTRY_PATH = PROJECT_ROOT / "_Agent" / "SKILL_REGISTRY.json"
SYNC_SCRIPT = PROJECT_ROOT / "_Agent" / "RUNNERS" / "sync_skill_wrappers.py"
GENERATED_MARKER = "Generated by _Agent/RUNNERS/sync_skill_wrappers.py"
CURRENT_ROOT = str(PROJECT_ROOT)
OLD_PROJECT_ROOT = "/Users/tindolhouse/Projects/" + "Tindol Family"
OLD_DOCS_PROJECT_ROOT = "/Users/tindolhouse/Documents/Claude/Projects/" + "Tindol Family"
OLD_PATHS = [
    OLD_PROJECT_ROOT,
    OLD_DOCS_PROJECT_ROOT + "/_Agent",
    OLD_DOCS_PROJECT_ROOT + "/",
]
STALE_SOCIAL = "08_Social_Media_" + "Melina"
SKIP_DIRS = {".git", "Docs", "__pycache__", "logs"}
TEXT_SUFFIXES = {".md", ".json", ".py", ".sh", ".plist", ".toml", ".txt", ".gitignore"}


def find_codex() -> str | None:
    if path := shutil.which("codex"):
        return path
    extension_root = Path.home() / ".vscode" / "extensions"
    if not extension_root.exists():
        return None
    candidates = sorted(extension_root.glob("*/bin/macos-aarch64/codex"))
    for candidate in reversed(candidates):
        if candidate.is_file():
            return str(candidate)
    return None


def find_gemini() -> str | None:
    if path := shutil.which("gemini"):
        return path
    nvm_root = Path.home() / ".nvm" / "versions" / "node"
    if not nvm_root.exists():
        return None
    candidates = sorted(nvm_root.glob("*/bin/gemini"))
    for candidate in reversed(candidates):
        if candidate.is_file():
            return str(candidate)
    return None


def load_skills() -> list[dict[str, str]]:
    data = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    skills = data.get("skills", [])
    if not isinstance(skills, list):
        raise AssertionError("_Agent/SKILL_REGISTRY.json has no skills list")
    return skills


def iter_text_files() -> list[Path]:
    paths: list[Path] = []
    for path in PROJECT_ROOT.rglob("*"):
        if any(part in SKIP_DIRS for part in path.relative_to(PROJECT_ROOT).parts):
            continue
        if not path.is_file():
            continue
        if path.name == ".DS_Store":
            continue
        if path.suffix in TEXT_SUFFIXES or path.name in {"AGENTS.md", "CLAUDE.md", "GEMINI.md", ".gitignore"}:
            paths.append(path)
    return paths


def check(condition: bool, message: str, errors: list[str]) -> None:
    if not condition:
        errors.append(message)


def main() -> int:
    errors: list[str] = []
    warnings: list[str] = []

    skills = load_skills()
    skill_names = [skill.get("name", "") for skill in skills]
    check(len(skill_names) == 16, f"Expected 16 registry skills, found {len(skill_names)}", errors)
    check(len(set(skill_names)) == len(skill_names), "Registry has duplicate skill names", errors)

    for skill in skills:
        source = PROJECT_ROOT / str(skill.get("source", ""))
        check(source.exists(), f"Missing canonical skill: {source}", errors)

    for base in [
        PROJECT_ROOT / ".agents" / "skills",
        PROJECT_ROOT / ".claude" / "skills",
    ]:
        for name in skill_names:
            check((base / name / "SKILL.md").exists(), f"Missing project wrapper: {base / name / 'SKILL.md'}", errors)

    for base in [Path.home() / ".codex" / "skills", Path.home() / ".claude" / "skills"]:
        found = [name for name in skill_names if (base / name / "SKILL.md").exists()]
        check(len(found) == 16, f"Expected 16 Tindol global wrappers under {base}, found {len(found)}", errors)

    for base in [PROJECT_ROOT / ".gemini" / "skills", Path.home() / ".gemini" / "skills"]:
        for name in skill_names:
            skill_file = base / name / "SKILL.md"
            if not skill_file.exists():
                continue
            text = skill_file.read_text(encoding="utf-8", errors="ignore")
            if GENERATED_MARKER in text:
                errors.append(f"Generated duplicate Gemini wrapper should be removed: {skill_file}")
            else:
                errors.append(f"Unmanaged Gemini wrapper conflicts with Tindol skill name: {skill_file}")

    sync = subprocess.run(
        [sys.executable, str(SYNC_SCRIPT), "--check", "--project", "--global"],
        cwd=PROJECT_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if sync.returncode != 0:
        errors.append("Skill wrapper sync check failed:\n" + sync.stderr.strip())

    for path in iter_text_files():
        text = path.read_text(encoding="utf-8", errors="ignore")
        for old in OLD_PATHS:
            if old in text:
                errors.append(f"Stale project path in {path.relative_to(PROJECT_ROOT)}: {old}")
        if STALE_SOCIAL in text:
            errors.append(f"Stale social folder reference in {path.relative_to(PROJECT_ROOT)}")

    check("--send" in (PROJECT_ROOT / "_Agent/SKILLS/slack/scripts/slack_send_message.py").read_text(), "Slack send script lacks --send gate", errors)
    check("--create" in (PROJECT_ROOT / "_Agent/SKILLS/google-workspace/scripts/calendar_create_event.py").read_text(), "Calendar create script lacks --create gate", errors)
    check("--create" in (PROJECT_ROOT / "_Agent/SKILLS/google-workspace/scripts/drive_create_text_file.py").read_text(), "Drive create script lacks --create gate", errors)

    local_settings = PROJECT_ROOT / ".claude" / "settings.local.json"
    if local_settings.exists():
        settings_text = local_settings.read_text(encoding="utf-8")
        check("//Users/" not in settings_text, ".claude/settings.local.json contains //Users paths", errors)

    gemini_settings = PROJECT_ROOT / ".gemini" / "settings.json"
    check(gemini_settings.exists(), ".gemini/settings.json is missing", errors)
    if gemini_settings.exists():
        settings = json.loads(gemini_settings.read_text(encoding="utf-8"))
        check(settings.get("general", {}).get("checkpointing", {}).get("enabled") is True, ".gemini/settings.json does not enable checkpointing", errors)
        check(settings.get("tools", {}).get("sandbox") is True, ".gemini/settings.json does not enable sandboxing", errors)
        check(settings.get("tools", {}).get("sandboxNetworkAccess") is True, ".gemini/settings.json does not enable sandbox network access", errors)
    gemini_command = PROJECT_ROOT / ".gemini" / "commands" / "daily-brief.toml"
    check(not gemini_command.exists(), ".gemini/commands/daily-brief.toml conflicts with the daily-brief skill command", errors)

    global_gemini = Path.home() / ".gemini" / "GEMINI.md"
    check(global_gemini.exists(), "~/.gemini/GEMINI.md is missing", errors)
    if global_gemini.exists():
        global_text = global_gemini.read_text(encoding="utf-8")
        check(CURRENT_ROOT in global_text, "~/.gemini/GEMINI.md does not reference the project root", errors)

    required_launcher_refs = [
        "_Agent/OPERATING_MANUAL.md",
        "_Agent/PROJECT_MAP.md",
        "_Agent/WORKFLOWS.md",
        "_Agent/SAFETY_PRIVACY.md",
        "_Agent/SKILLS/",
    ]
    for launcher in ["AGENTS.md", "CLAUDE.md", "GEMINI.md"]:
        launcher_text = (PROJECT_ROOT / launcher).read_text(encoding="utf-8")
        for ref in required_launcher_refs:
            check(ref in launcher_text, f"{launcher} does not reference {ref}", errors)
        check("family alias" not in launcher_text, f"{launcher} still describes family as an alias", errors)
        check("`family` shell helper" in launcher_text, f"{launcher} does not describe family as a shell helper", errors)
        check("family use gemini" in launcher_text, f"{launcher} does not document family use gemini", errors)

    codex_config = Path.home() / ".codex" / "config.toml"
    if codex_config.exists():
        config_text = codex_config.read_text(encoding="utf-8")
        check('project_root_markers = [".git", "AGENTS.md"]' in config_text, "~/.codex/config.toml lacks project_root_markers", errors)
    else:
        warnings.append("~/.codex/config.toml not found")

    if not find_codex():
        errors.append("codex command not found on PATH")
    if not find_gemini():
        errors.append("gemini command not found on PATH")
    if not shutil.which("claude"):
        warnings.append("claude command not found on PATH; family should fall back if active tool is claude")

    for warning in warnings:
        print(f"WARNING: {warning}")
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print("Interoperability checks passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
