#!/usr/bin/env python3
"""Generate Codex and Claude skill wrappers from the Tindol skill registry.

Gemini CLI loads repo skills through the .agents/skills alias, so this script
intentionally does not generate .gemini/skills or ~/.gemini/skills wrappers.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
REGISTRY_PATH = PROJECT_ROOT / "_Agent" / "SKILL_REGISTRY.json"
GENERATED_MARKER = "Generated by _Agent/RUNNERS/sync_skill_wrappers.py"


def _yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def load_registry() -> list[dict[str, str]]:
    data = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    skills = data.get("skills", [])
    if not isinstance(skills, list):
        raise SystemExit("Registry error: skills must be a list.")

    seen: set[str] = set()
    normalized: list[dict[str, str]] = []
    for skill in skills:
        name = str(skill.get("name", "")).strip()
        source = str(skill.get("source", "")).strip()
        description = str(skill.get("description", "")).strip()
        title = str(skill.get("title", name)).strip()
        short_description = str(skill.get("short_description", f"Tindol Family - {title}")).strip()
        if not name or not source or not description:
            raise SystemExit(f"Registry error: {skill!r} needs name, source, and description.")
        if name in seen:
            raise SystemExit(f"Registry error: duplicate skill name {name!r}.")
        seen.add(name)
        source_path = PROJECT_ROOT / source
        if not source_path.exists():
            raise SystemExit(f"Registry error: source file missing for {name}: {source}")
        normalized.append(
            {
                "name": name,
                "source": source,
                "description": description,
                "title": title,
                "short_description": short_description,
            }
        )
    return normalized


def wrapper_text(skill: dict[str, str], *, tool: str, global_wrapper: bool) -> str:
    source_path = PROJECT_ROOT / skill["source"]
    lines = [
        "---",
        f"name: {skill['name']}",
        f"description: {_yaml_string(skill['description'])}",
    ]
    if tool == "codex":
        lines.extend(
            [
                "metadata:",
                f"  short-description: {_yaml_string(skill['short_description'])}",
            ]
        )
    lines.extend(
        [
            "---",
            "",
            f"<!-- {GENERATED_MARKER}; do not edit by hand. -->",
            "",
            f"# {skill['title']} (Tindol Family Hub)",
            "",
            "This is a generated wrapper for a canonical Tindol Family Hub skill.",
            "",
            "## Project Root",
            "",
            str(PROJECT_ROOT),
            "",
            "## Canonical Skill",
            "",
            str(source_path),
            "",
            "## Instructions",
            "",
            "1. Change to the project root if you are not already there.",
            "2. Read the canonical skill file above.",
            "3. Follow the canonical skill workflow and safety rules.",
            "",
        ]
    )
    if global_wrapper:
        lines.extend(
            [
                "This global wrapper exists so the skill can be invoked from any directory.",
                "If the project root path changes, regenerate wrappers from the repo.",
                "",
            ]
        )
    return "\n".join(lines)


def target_paths(skills: list[dict[str, str]], *, project: bool, global_target: bool) -> list[tuple[Path, str, bool, str]]:
    targets: list[tuple[Path, str, bool, str]] = []
    for skill in skills:
        if project:
            targets.append((PROJECT_ROOT / ".agents" / "skills" / skill["name"] / "SKILL.md", "codex", False, skill["name"]))
            targets.append((PROJECT_ROOT / ".claude" / "skills" / skill["name"] / "SKILL.md", "claude", False, skill["name"]))
        if global_target:
            targets.append((Path.home() / ".codex" / "skills" / skill["name"] / "SKILL.md", "codex", True, skill["name"]))
            targets.append((Path.home() / ".claude" / "skills" / skill["name"] / "SKILL.md", "claude", True, skill["name"]))
    return targets


def clean_project_targets(skills: list[dict[str, str]], *, project: bool, check: bool) -> list[str]:
    if not project:
        return []
    errors: list[str] = []
    expected = {skill["name"] for skill in skills}
    for base in [
        PROJECT_ROOT / ".agents" / "skills",
        PROJECT_ROOT / ".claude" / "skills",
    ]:
        if not base.exists():
            continue
        for skill_file in base.glob("*/SKILL.md"):
            if skill_file.parent.name in expected:
                continue
            text = skill_file.read_text(encoding="utf-8")
            if GENERATED_MARKER not in text:
                errors.append(f"Unmanaged project skill wrapper present: {skill_file}")
                continue
            if check:
                errors.append(f"Generated stale project wrapper present: {skill_file}")
            else:
                skill_file.unlink()
                try:
                    skill_file.parent.rmdir()
                except OSError:
                    pass
    return errors


def clean_gemini_duplicate_targets(skills: list[dict[str, str]], *, project: bool, global_target: bool, check: bool) -> list[str]:
    """Remove generated Gemini wrappers that would duplicate .agents/skills."""
    errors: list[str] = []
    bases: list[Path] = []
    if project:
        bases.append(PROJECT_ROOT / ".gemini" / "skills")
    if global_target:
        bases.append(Path.home() / ".gemini" / "skills")

    for base in bases:
        if not base.exists():
            continue
        for skill in skills:
            skill_file = base / skill["name"] / "SKILL.md"
            if not skill_file.exists():
                continue
            text = skill_file.read_text(encoding="utf-8")
            if GENERATED_MARKER not in text:
                errors.append(f"Unmanaged Gemini skill wrapper conflicts with Tindol skill: {skill_file}")
                continue
            if check:
                errors.append(f"Generated duplicate Gemini wrapper present: {skill_file}")
            else:
                skill_file.unlink()
                try:
                    skill_file.parent.rmdir()
                except OSError:
                    pass
    return errors


def sync(check: bool, project: bool, global_target: bool) -> int:
    skills = load_registry()
    errors = clean_project_targets(skills, project=project, check=check)
    errors.extend(clean_gemini_duplicate_targets(skills, project=project, global_target=global_target, check=check))

    by_name = {skill["name"]: skill for skill in skills}
    for path, tool, is_global, name in target_paths(skills, project=project, global_target=global_target):
        expected = wrapper_text(by_name[name], tool=tool, global_wrapper=is_global)
        if check:
            if not path.exists():
                errors.append(f"Missing wrapper: {path}")
                continue
            actual = path.read_text(encoding="utf-8")
            if actual != expected:
                errors.append(f"Wrapper drift: {path}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")

    if check:
        if errors:
            for error in errors:
                print(error, file=sys.stderr)
            return 1
        print("Skill wrappers are in sync.")
    else:
        scope = []
        if project:
            scope.append("project")
        if global_target:
            scope.append("global")
        print(f"Generated {len(skills)} skills for {', '.join(scope)} targets.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check generated wrappers without writing.")
    parser.add_argument("--project", action="store_true", help="Generate/check repo-native wrappers.")
    parser.add_argument("--global", dest="global_target", action="store_true", help="Generate/check home-directory wrappers.")
    args = parser.parse_args()

    project = args.project
    global_target = args.global_target
    if not project and not global_target:
        project = True
        global_target = True

    if shutil.which("python3") is None:
        raise SystemExit("python3 is required.")

    return sync(args.check, project, global_target)


if __name__ == "__main__":
    raise SystemExit(main())
